project:
  type: website

website:
  title: "POT OF GREED"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Card Statistics"
        href: stats.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Yu-Gi-Oh! Website"
        href: https://your-main-website-link-here.com

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  echo: false
  warning: false
  message: false
