project:
  type: website
  output-dir: docs

website:
  title: "Draw 2 Cards"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Card Statistics"
        href: stats.qmd
      - text: "Cards"
        href: cards.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Pot Of Greed"
        href: https://karlnmatias.github.io/Yugioh/

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  echo: false
  warning: false
  message: false
